### ISSUE TITLE
Equality relation for floats

### ISSUE THREAD

**Issue by emilv** [dndubins/QuickStats#1]
[Equality comparison](https://github.com/dndubins/QuickStats/blob/d269755cde5f6daed04e65c37b8880563583b8db/QuickStats.cpp#L138) doesn't really make sense for floats since floating point values are not exact. Normally you would compare the difference towards a small value, such as:

    sorted[i]-sorted[i-1] > 0.00001

The constant is usually called an *epsilon* and can be chosen differently depending on context.

It would probably be best to compare to the first number in the current series (`sorted[i]-sorted[firstInSeries]`). And perhaps allow the user to specify the epsilon value as a function argument.

**Comment by dndubins** [comment]
Thank you for having a look at this library, and for your help! It is much appreciated. I also really like the clarity in the description of your point. I have incorporated epsilon in the calculation of mode, and updated the library. I also added geometric mean while I was at it.
One thing I realized later was that I never test for NaN values, and they will crash the functions. I debated filtering for NaN values in the routines, but then decided that this is probably something that should be done prior to statistics.

**Comment by emilv** [comment]
Nice work! I like how small and simple this library is. I found while searching for a simple sort implementation for Android. Now I'm thinking about building my own sort-only library for the purpose because everyone just seems to throw in bubble sort and call it a day :-)

I moved the discussion of NaNs to #2 to keep issues on topic.
