### ISSUE TITLE
Mode not counting correctly

### ISSUE THREAD

**Issue by Jconnor20** [dndubins/QuickStats#3]
Hi just went to use the library as it has the mode function I was looking for. However, I noticed that it wasn't counting the number of times a variable was present in array correctly. 

I found a fix. By adding a new variable into the mode function 
         int pw = 0;
Changing the If state below in the for loop 
        if(abs(sorted[i]-sorted[pw]) < epsilon)
And then adding the below line into the else statement
       np = i;
     
This seemed to fix my issue. I have tested it outside what I'm trying to do so I'm not if there will be conditions that break the code.
 Hope this helps 
Jack

**Comment by dndubins** [comment]
Thanks Jack! Much appreciated. I just saw this, sorry for the long delay in answering. Do you have a test data set you could send me that doesn't work with the old code? If not that's ok, I can try to come up with my own. I noticed you switched from fabs() to abs() in the if() statement. Was this intentional? fabs() is for float numbers.
Kind regards, 
Dave

**Comment by Jconnor20** [comment]
Hi Dave,

No worries I kinda forgot that I fixed the mode counting. Unfortunately I
don't have any test day because I was using raw sensor data. I think it was
an IR sharp5m sensor for reference. In terms of the use of abs() that was a
mistake on my part.  For data try using the data set below, its roughly the
same data to what my sensor was outputting.

59.4
59.4
48.6
59.4
62.3
62.3
62.3
59.4
62.3
49.7

If you have any more questions please let me know.

Thanks,
Jack Connor

**Comment by dndubins** [comment]
I've re-written the mode routine. You are right! Mode didn't work on your data set at all. Thanks for finding this error, Jack! I'm so sorry it took so long for me to do this. I don't open this library very often.
